/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mcrouter/lib/network/gen-cpp2/mc_caret_protocol_constants.h"

namespace facebook { namespace memcache { namespace cpp2 {

}}} // facebook::memcache::cpp2