/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "mcrouter/lib/network/gen-cpp2/mc_caret_protocol_types.h"
#include <thrift/lib/cpp2/protocol/Protocol.h>
namespace facebook { namespace memcache { namespace cpp2 {

struct mc_caret_protocol_constants {};

class __attribute__((__deprecated__("mc_caret_protocolConstants suffers from the 'static initialization order fiasco' (https://isocpp.org/wiki/faq/ctors#static-init-order) and may CRASH you program. Instead, use mc_caret_protocol_constants::CONSTANT_NAME()"))) mc_caret_protocolConstants {
 public:
  mc_caret_protocolConstants() {}
};

}}} // facebook::memcache::cpp2